version: '2'
services:
  jenkinsmaster:
    build: .
    image: 388562162178.dkr.ecr.us-east-1.amazonaws.com/jenkins:latest
    container_name: jenkinsmaster
    ports:
     - "8080:8080"
     - "5000:5000"
    volumes:
     - jenkins-data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      COMPOSER_HOME: /var/jenkins_home/.composer
      COMPOSE_HTTP_TIMEOUT: 240
volumes:
  jenkins-data: {}
